# Basic
title: Tan's Blog
author: Tanmengwen
description: An engineer

baseurl:           ""
url:               "http://tanmengwen.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "pages/:num/"

# Social
social:
    # weibo: Tanmengwen
    github: Tanmengwen
    # gplus: 112547382138552250597
    mail: mengwent@gmail.com
